version: '3'

services:


  webhook:
    build: .
    image: webh
    ports:
      - 5000:5000
    extra_hosts:
      - "127.0.0.1:192.168.0.6"

  ngrok:
    image: wernight/ngrok
    command: ngrok http --region=eu --authtoken 2KM7QYmKzUjTD5niWe60KvdonvL_J21LRhcEhQDgBnEa9bAo webhook:5000 
    ports:
      - 4040:4040
    
    
    
    
  #our_db:
    #ports:
   #   - 5432:5432
   # environment:
   #   - POSTGRES_PASSWORD=semen
   #   - POSTGRES_USER=postgres
   # image: postgres:15.3-alpine